name: LumaItems
version: '${version}'
main: dev.jsinco.lumaitems.LumaItems
api-version: '1.20'
softdepend: [PlaceHolderAPI, EvenMoreFish] # Softdepending EMF to register listeners after
author: 'Jsinco'
permissions:
  lumaitems.command.give:
    description: Gives a player a LumaItem
    default: op
  lumaitems.command.pinatafile:
    description: Internal command for adding items to pinata ability prizepool
    default: false
  lumaitems.command.stellarstar:
    description: Command to give a player a Stellar Star
    default: op
commands:
  lumaitems:
    description: LumaItems command
    permission: lumaitems.command
    usage: /<command>
